### PR TITLE
Update Account.java

### PR DESCRIPTION
**Pull request by kevalporiya**
changes to the account.java class file

### CODE REVIEW

**Comment by kevalporiya** [comment]
granted

**Comment by TYuVenngage** [comment]
Hi @kevalporiya,

This is Thomson from Venngage. Please create a fork of this repo and push your code to your fork. 
Thanks!

**Comment by kevalporiya** [comment]
Okay sure ..
Thank you
Keval

**Comment by kevalporiya** [comment]
Hello An Vo ,
I am sending you my github link along with answers to your questions in
this document file .
Please take a look and let me know for further details.
I am waiting for your feedback.
Thank You
Keval.

**Pull request closed without merging**
